export const venues = [
  {
    id: 1,
    name: 'Sky Lounge',
    rating: 4.8,
    image: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
    category: 'Clubs',
    location: 'Connaught Place',
    price: '₹₹₹',
  },
  {
    id: 2,
    name: 'Neon Club',
    rating: 4.6,
    image: 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg',
    category: 'Clubs',
    location: 'Cyber Hub',
    price: '₹₹₹₹',
  },
  {
    id: 3,
    name: 'Garden Villa',
    rating: 4.9,
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg',
    category: 'FarmHouse',
    location: 'Gurgaon',
    price: '₹₹',
  },
  {
    id: 4,
    name: 'Urban Bistro',
    rating: 4.4,
    image: 'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg',
    category: 'Restaurant',
    location: 'Khan Market',
    price: '₹₹',
  },
  {
    id: 5,
    name: 'Rooftop Terrace',
    rating: 4.7,
    image: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg',
    category: 'Bar',
    location: 'Hauz Khas',
    price: '₹₹₹',
  },
  {
    id: 6,
    name: 'Private Lounge',
    rating: 4.5,
    image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg',
    category: 'HouseParty',
    location: 'South Delhi',
    price: '₹₹',
  },
];

export const events = [
  {
    id: 1,
    name: 'Summer Rooftop Party',
    venue: 'Sky Lounge',
    date: '25 Dec 2024',
    time: '8:00 PM',
    image: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
    status: 'confirmed',
    attendees: 45,
    category: 'Party',
  },
  {
    id: 2,
    name: 'New Year Bash',
    venue: 'Club Infinity',
    date: '31 Dec 2024',
    time: '10:00 PM',
    image: 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg',
    status: 'pending',
    attendees: 120,
    category: 'Party',
  },
  {
    id: 3,
    name: 'Birthday Celebration',
    venue: 'Private Villa',
    date: '15 Jan 2025',
    time: '7:00 PM',
    image: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg',
    status: 'confirmed',
    attendees: 25,
    category: 'Birthday',
  },
  {
    id: 4,
    name: 'Corporate Mixer',
    venue: 'Business Center',
    date: '20 Jan 2025',
    time: '6:00 PM',
    image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg',
    status: 'confirmed',
    attendees: 80,
    category: 'Corporate',
  },
];

export const farmhouses = [
  {
    id: 1,
    name: 'Green Valley Farmhouse',
    location: 'Gurgaon',
    price: '₹15,000/day',
    rating: 4.8,
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg',
    amenities: ['Pool', 'Garden', 'BBQ', 'AC'],
    capacity: '20-30 people',
  },
  {
    id: 2,
    name: 'Sunset Villa',
    location: 'Manesar',
    price: '₹25,000/day',
    rating: 4.9,
    image: 'https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg',
    amenities: ['Pool', 'Garden', 'AC'],
    capacity: '30-40 people',
  },
  {
    id: 3,
    name: 'Royal Retreat',
    location: 'Sohna',
    price: '₹35,000/day',
    rating: 4.7,
    image: 'https://images.pexels.com/photos/1396125/pexels-photo-1396125.jpeg',
    amenities: ['Pool', 'Garden', 'BBQ', 'AC'],
    capacity: '40-50 people',
  },
];

export const restaurants = [
  {
    id: 1,
    name: 'The Sky Lounge',
    cuisine: 'Continental',
    location: 'Connaught Place',
    price: '₹₹₹',
    rating: 4.6,
    image: 'https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg',
    category: 'Fine Dining',
    features: ['Live Music', 'Rooftop', 'Bar'],
    timing: '6 PM - 2 AM',
  },
  {
    id: 2,
    name: 'Urban Bistro',
    cuisine: 'Italian',
    location: 'Khan Market',
    price: '₹₹',
    rating: 4.4,
    image: 'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg',
    category: 'Casual',
    features: ['Outdoor Seating', 'WiFi'],
    timing: '12 PM - 11 PM',
  },
  {
    id: 3,
    name: 'Neon Nights',
    cuisine: 'Asian Fusion',
    location: 'Cyber Hub',
    price: '₹₹₹₹',
    rating: 4.8,
    image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg',
    category: 'Bar',
    features: ['DJ', 'Dance Floor', 'Premium Bar'],
    timing: '7 PM - 3 AM',
  },
];